project:
  type: website

website:
  title: "Technical ramblings"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/rahulunair
      - icon: twitter
        href: https://twitter.com/unrahu1

format:
  html:
    theme: 
      light: [journal] 
      dark: [vapor]



