project:
  type: website

website:
  title: "Technical ramblings"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/rahulunair
      - icon: twitter
        href: https://twitter.com/unrahu1
format:
  html:
    theme: simplex
    css: styles.css



