<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="unrahul">
<meta name="dcterms.date" content="2026-08-16">
<meta name="description" content="A four-bit Qwen3.8-27B build for Intel Arc Pro B-series GPUs: 37.8 tok/s on two B65 cards, 52.1 on four, and what the measurements said along the way.">

<title>Qwen3.8-27B on Intel Arc Pro: two cards, near four-card speed – Technical ramblings</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5fa59ed1e8650c07c21602d74879e908.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-568df3714da8cbef77d69c472e6ea8a1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-5fa59ed1e8650c07c21602d74879e908.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-c494543206d00ebf67c85e3545d33d4e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-38e3489f5ae581b1557cc87873ccb062.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-c494543206d00ebf67c85e3545d33d4e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<meta property="og:title" content="Qwen3.8-27B on Intel Arc Pro: two cards, near four-card speed – Technical ramblings">
<meta property="og:description" content="A four-bit Qwen3.8-27B build for Intel Arc Pro B-series GPUs: 37.8 tok/s on two B65 cards, 52.1 on four, and what the measurements said along the way.">
<meta property="og:image" content="https://blog.rahul.onl/posts/qwen38-27b/card.png">
<meta property="og:site_name" content="Technical ramblings">
<meta property="og:image:height" content="789">
<meta property="og:image:width" content="1200">
<meta property="og:image:alt" content="Four measured W4A16 paths on two Intel Arc Pro B65 cards, rising from 6.2 to 35.1 tokens per second.">
<meta name="twitter:title" content="Qwen3.8-27B on Intel Arc Pro: two cards, near four-card speed – Technical ramblings">
<meta name="twitter:description" content="A four-bit Qwen3.8-27B build for Intel Arc Pro B-series GPUs: 37.8 tok/s on two B65 cards, 52.1 on four, and what the measurements said along the way.">
<meta name="twitter:image" content="https://blog.rahul.onl/posts/qwen38-27b/card.png">
<meta name="twitter:creator" content="@108brushes">
<meta name="twitter:image-height" content="789">
<meta name="twitter:image-width" content="1200">
<meta name="twitter:image:alt" content="Four measured W4A16 paths on two Intel Arc Pro B65 cards, rising from 6.2 to 35.1 tokens per second.">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Technical ramblings</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/rahulunair"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://x.com/108brushes"> <i class="bi bi-twitter-x" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Qwen3.8-27B on Intel Arc Pro: two cards, near four-card speed</h1>
            <p class="subtitle lead">An 18.2 GiB four-bit build that decodes at 37.8 tok/s on two B65 cards, within 9% of the official FP8 checkpoint on four.</p>
                  <div>
        <div class="description">
          A four-bit Qwen3.8-27B build for Intel Arc Pro B-series GPUs: 37.8 tok/s on two B65 cards, 52.1 on four, and what the measurements said along the way.
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">intel</div>
                <div class="quarto-category">arc</div>
                <div class="quarto-category">arc-pro</div>
                <div class="quarto-category">xe2</div>
                <div class="quarto-category">xpu</div>
                <div class="quarto-category">sglang</div>
                <div class="quarto-category">llm-inference</div>
                <div class="quarto-category">quantization</div>
                <div class="quarto-category">agentic-coding</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>unrahul </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">August 16, 2026</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#running-it" id="toc-running-it" class="nav-link active" data-scroll-target="#running-it">Running it</a></li>
  <li><a href="#what-are-we-actually-running" id="toc-what-are-we-actually-running" class="nav-link" data-scroll-target="#what-are-we-actually-running">What are we actually running?</a></li>
  <li><a href="#before-writing-a-kernel-do-the-boring-math" id="toc-before-writing-a-kernel-do-the-boring-math" class="nav-link" data-scroll-target="#before-writing-a-kernel-do-the-boring-math">Before writing a kernel, do the boring math</a></li>
  <li><a href="#check-upstream-first-then-add-the-missing-bits" id="toc-check-upstream-first-then-add-the-missing-bits" class="nav-link" data-scroll-target="#check-upstream-first-then-add-the-missing-bits">Check upstream first, then add the missing bits</a></li>
  <li><a href="#the-existing-library-primitive-was-the-fastest-kernel-i-tested" id="toc-the-existing-library-primitive-was-the-fastest-kernel-i-tested" class="nav-link" data-scroll-target="#the-existing-library-primitive-was-the-fastest-kernel-i-tested">The existing library primitive was the fastest kernel I tested</a></li>
  <li><a href="#four-bits-is-not-really-four-bits" id="toc-four-bits-is-not-really-four-bits" class="nav-link" data-scroll-target="#four-bits-is-not-really-four-bits">Four bits is not really four bits</a></li>
  <li><a href="#graph-capture-changes-both-performance-and-observability" id="toc-graph-capture-changes-both-performance-and-observability" class="nav-link" data-scroll-target="#graph-capture-changes-both-performance-and-observability">Graph capture changes both performance and observability</a></li>
  <li><a href="#the-trace-blamed-the-wrong-component" id="toc-the-trace-blamed-the-wrong-component" class="nav-link" data-scroll-target="#the-trace-blamed-the-wrong-component">The trace blamed the wrong component</a></li>
  <li><a href="#the-final-latency-distribution-is-pleasantly-boring" id="toc-the-final-latency-distribution-is-pleasantly-boring" class="nav-link" data-scroll-target="#the-final-latency-distribution-is-pleasantly-boring">The final latency distribution is pleasantly boring</a></li>
  <li><a href="#what-might-b70-do" id="toc-what-might-b70-do" class="nav-link" data-scroll-target="#what-might-b70-do">What might B70 do?</a></li>
  <li><a href="#a-quick-detour-through-the-other-models" id="toc-a-quick-detour-through-the-other-models" class="nav-link" data-scroll-target="#a-quick-detour-through-the-other-models">A quick detour through the other models</a></li>
  <li><a href="#what-were-codex-and-claude-actually-useful-for" id="toc-what-were-codex-and-claude-actually-useful-for" class="nav-link" data-scroll-target="#what-were-codex-and-claude-actually-useful-for">What were Codex and Claude actually useful for?</a></li>
  <li><a href="#fast-gibberish-is-still-gibberish" id="toc-fast-gibberish-is-still-gibberish" class="nav-link" data-scroll-target="#fast-gibberish-is-still-gibberish">Fast gibberish is still gibberish</a></li>
  <li><a href="#what-still-does-not-make-sense" id="toc-what-still-does-not-make-sense" class="nav-link" data-scroll-target="#what-still-does-not-make-sense">What still does not make sense?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">






<p>Qwen3.8-27B decodes at <strong>37.8 tokens per second on two Intel Arc Pro B65 cards</strong>, which lands within 9% of what the official FP8 checkpoint does on <strong>four</strong>. Give the same four-bit build all four cards and it reaches <strong>52.1 tok/s</strong>. Halving the hardware for a workload like this is the result I care about most, and it came from a quantization decision rather than a new kernel.</p>
<p>I wanted <a href="https://huggingface.co/Qwen/Qwen3.8-27B">Qwen3.8-27B</a> as the local backend for coding agents: good at code, useful at long context, small enough to run on a few GPUs. Local agents make latency personal. A slow token is not a number in a benchmark, it is an interruption while you are editing a file, searching a repository, or waiting on a tool call.</p>
<p>Getting there took longer than expected. The model is dense, multimodal, and mostly built from Gated DeltaNet layers. It has a multi-token-prediction head, a vision tower, and enough different execution regimes that a change which looks great in a standalone kernel can vanish, or turn into a regression, once it is inside the server.</p>
<p>The interesting results were not heroic. The largest four-bit step came from a library primitive that already existed. Group size 128 beat group size 32. A cost I had written off as fixed host overhead turned out to be dense device work. And the 48 DeltaNet layers I expected to dominate decode were not where most of the time went.</p>
<p>This is independent work I did in my free time on hardware available to me. It is not an Intel release or an official Intel performance result. Intel XPU support has been arriving quickly in SGLang and the surrounding stack, so the job here was to optimize this particular model and add the model-specific pieces missing from the version I used. Before applying anything described below, check whether current upstream already has it.</p>
<blockquote class="blockquote">
<p><strong>Scope of the numbers:</strong> every measured Qwen3.8 result here is on Intel Arc Pro B65 GPUs. The B70 section is an estimate, clearly marked, not a Qwen3.8 measurement. “Decode tok/s” means <code>1000 / TPOT</code> at the stated context and concurrency; it is not the benchmark’s output-throughput field, which folds time-to-first-token into the same wall-clock interval.</p>
</blockquote>
<section id="running-it" class="level2">
<h2 class="anchored" data-anchor-id="running-it">Running it</h2>
<p>If you only want the model serving, this is the setup I use daily: four Arc Pro B65 cards at tensor parallelism 4, the model’s full 256K context, and enough room configured for several requests in flight at once. A single stream decodes at 52.1 tok/s on an 8K prompt, and token-to-token latency stays flat as the context fills.</p>
<p>The weights are at <a href="https://huggingface.co/ulkaa/Qwen3.8-27B-AWQ-INT4"><code>ulkaa/Qwen3.8-27B-AWQ-INT4</code></a> and the pinned serving image is on Docker Hub as <a href="https://hub.docker.com/r/rahulunair/sglang-xpu"><code>rahulunair/sglang-xpu</code></a>, tag <code>qwen3.8-27b-20260816</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">docker</span> run <span class="at">--rm</span> <span class="at">--device</span><span class="op">=</span>/dev/dri <span class="at">-v</span> /dev/dri:/dev/dri <span class="dt">\</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">--group-add</span> video <span class="at">--group-add</span> <span class="st">"</span><span class="va">$(</span><span class="fu">getent</span> group render <span class="kw">|</span> <span class="fu">cut</span> <span class="at">-d:</span> <span class="at">-f3</span><span class="va">)</span><span class="st">"</span> <span class="dt">\</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">--cap-add</span><span class="op">=</span>SYS_PTRACE <span class="at">--security-opt</span> seccomp=unconfined <span class="dt">\</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">--ipc</span><span class="op">=</span>host <span class="at">--shm-size</span><span class="op">=</span>64g <span class="at">--ulimit</span> memlock=-1 <span class="dt">\</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">-p</span> 30000:30000 <span class="at">-v</span> /path/to/Qwen3.8-27B-AWQ-INT4:/model:ro <span class="dt">\</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">-e</span> ONEAPI_DEVICE_SELECTOR=level_zero:gpu <span class="dt">\</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  rahulunair/sglang-xpu:qwen3.8-27b-20260816 <span class="dt">\</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  python <span class="at">-m</span> sglang.launch_server <span class="at">--model-path</span> /model <span class="at">--device</span> xpu <span class="dt">\</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">--tp-size</span> 4 <span class="at">--attention-backend</span> intel_xpu <span class="at">--page-size</span> 64 <span class="dt">\</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">--context-length</span> 262144 <span class="dt">\</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">--chunked-prefill-size</span> 4096 <span class="at">--mem-fraction-static</span> 0.85 <span class="dt">\</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">--cuda-graph-config</span> <span class="st">'{"decode":{"backend":"full","bs":[1,2,4,8]},"prefill":{"backend":"disabled"}}'</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Use <code>--tp-size 2</code> on a two-card machine, where the same prompt decodes at 37.8 tok/s. Leaving <code>--max-total-tokens</code> unset lets the server size the KV pool from the memory it finds; pin it lower if you are sharing the cards with something else. The <code>SYS_PTRACE</code> and unconfined seccomp flags are there for one optional fast collective I describe later; drop both and the model still runs normally.</p>
<p>Do check current upstream SGLang and Intel images before reaching for a pinned image. A pinned release is useful for reproducing this article, not evidence that its patch set deserves to live forever.</p>
<p>The rest of this post is how I got there, for anyone who wants the reasoning rather than the recipe.</p>
</section>
<section id="what-are-we-actually-running" class="level2">
<h2 class="anchored" data-anchor-id="what-are-we-actually-running">What are we actually running?</h2>
<p>Qwen3.8-27B has 64 decoder layers. Forty-eight use Gated DeltaNet, a linear attention recurrence, and 16 use full attention. It is dense rather than mixture-of-experts, so almost every large text-model weight participates in every decode step. The checkpoint also carries a 27-layer vision tower and a multi-token-prediction head.</p>
<p>That shape splits the problem into two regimes:</p>
<ul>
<li><strong>Decode at batch one</strong> has very little arithmetic reuse. It is mostly a question of how many bytes must cross memory for every new token, plus small kernels, layer boundaries, and collectives.</li>
<li><strong>Prefill</strong> turns the same projections into larger matrix operations and adds context-growing attention work. Compute throughput and tile efficiency matter much more here.</li>
</ul>
<p>I kept two checkpoints working throughout.</p>
<ol type="1">
<li>The official <a href="https://huggingface.co/Qwen/Qwen3.8-27B-FP8">Qwen3.8-27B-FP8</a> checkpoint, my reference while getting everything working.</li>
<li>My <a href="https://huggingface.co/ulkaa/Qwen3.8-27B-AWQ-INT4">Qwen3.8-27B AWQ W4A16</a> checkpoint: 18.2 GiB, asymmetric group-128 quantization, BF16 vision tower and MTP tensors preserved.</li>
</ol>
<p>“FP8 model” and “AWQ model” describe how a checkpoint stores its weights, not necessarily the instruction that runs every projection. The runtime may dequantize into BF16, keep an extra signed-INT8 copy for decode, or dispatch a genuine four-bit primitive. Keeping storage precision, activation precision, and selected kernel separate in my head avoided a lot of confusion.</p>
<p>These are the final runs. Output was coherent, graph replay and the expected fast paths were active, and I used the second run of each shape. Earlier numbers helped me debug the model but are not useful baselines.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>model and setup</th>
<th style="text-align: right;">GPUs / TP</th>
<th style="text-align: right;">input / output</th>
<th style="text-align: right;">TTFT</th>
<th style="text-align: right;">prefill, TTFT-derived</th>
<th style="text-align: right;">TPOT</th>
<th style="text-align: right;">decode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>official FP8, optimized dense decode setup</td>
<td style="text-align: right;">4x B65 / TP4</td>
<td style="text-align: right;">8K / 1K</td>
<td style="text-align: right;">2,313 ms</td>
<td style="text-align: right;">3,542 tok/s</td>
<td style="text-align: right;">24.17 ms</td>
<td style="text-align: right;"><strong>41.4 tok/s</strong></td>
</tr>
<tr class="even">
<td>AWQ group 128, oneDNN W4A16</td>
<td style="text-align: right;">2x B65 / TP2</td>
<td style="text-align: right;">8K / 1K</td>
<td style="text-align: right;">4,479 ms</td>
<td style="text-align: right;">1,829 tok/s</td>
<td style="text-align: right;">26.44 ms</td>
<td style="text-align: right;"><strong>37.8 tok/s</strong></td>
</tr>
<tr class="odd">
<td>AWQ group 128, oneDNN W4A16</td>
<td style="text-align: right;">4x B65 / TP4</td>
<td style="text-align: right;">8K / 1K</td>
<td style="text-align: right;">2,749 ms</td>
<td style="text-align: right;">2,980 tok/s</td>
<td style="text-align: right;">19.20 ms</td>
<td style="text-align: right;"><strong>52.1 tok/s</strong></td>
</tr>
</tbody>
</table>
<p><em>These are complete setups, not a one-change-at-a-time comparison: graph capture on, concurrency 1, second run, roughly 9K context at the end of decode.</em></p>
<p>The first two rows are the ones I keep coming back to. Two cards running my four-bit build land at 37.8 tok/s against 41.4 for the official checkpoint on four. I would not turn that into an efficiency percentage, because the two rows use different checkpoint formats and different code paths. As a practical statement about hardware, though, it is the whole point: the same class of interactive experience, on half the cards.</p>
<p>The official FP8 checkpoint stays useful. It is the standard model, it works in the release image, and it helped me separate genuine model behaviour from bugs in my own quantization pipeline.</p>
</section>
<section id="before-writing-a-kernel-do-the-boring-math" class="level2">
<h2 class="anchored" data-anchor-id="before-writing-a-kernel-do-the-boring-math">Before writing a kernel, do the boring math</h2>
<p>The first question about any operator is whether it is limited by arithmetic or by memory traffic:</p>
<pre class="text"><code>time &gt;= max(useful_FLOPs / achievable_FLOPs_per_second,
            bytes_moved / achievable_bytes_per_second)</code></pre>
<p>For batch-one dense decode, arithmetic intensity is close to one operation per weight byte. The memory term wins quickly, so the first useful model is just counting bytes:</p>
<pre class="text"><code>bytes_per_token = sum(weights and metadata read by one decode step)
seconds_per_token = bytes_per_token / aggregate_achievable_bandwidth
tokens_per_second = 1 / seconds_per_token</code></pre>
<p>Count from the <code>safetensors</code> headers, not from a number in <code>config.json</code>. An embedding table is resident but only one row gets looked up. The vision tower is resident but idle during a text-only turn. The MTP head is only read when speculation is active. On a multimodal model, counting every resident tensor can add several GiB the step never actually reads.</p>
<p>Quantization metadata counts too. A nominal four-bit weight with group scales and zero points is not exactly 0.5 bytes per parameter. In this format it is about 0.52 bytes at group 128 and about 0.59 at group 32, and that metadata is read alongside the payload on every token.</p>
<p>Prefill is a different calculation. A reasonable first approximation for the dense projections is <code>2 × parameters × prompt_tokens</code> floating-point operations, with the attention term added separately. This is why one number called “model throughput” should never be used for both phases.</p>
<p>Intel lists both the B65 and the B70 at 32 GiB and 608 GB/s of memory bandwidth. The B65 has 20 Xe2 cores and 197 peak dense INT8 TOPS; the B70 has 32 cores and 367 TOPS. Same advertised bandwidth, roughly 1.86x the INT8 compute. Decode and prefill should therefore scale differently even before software enters the picture.</p>
<p>A roofline is not a target. It is a boundary and a smell detector. It tells you when a proposed optimization cannot possibly repay its complexity, when a measurement looks suspiciously good, and when writing another kernel is unlikely to be the best use of the time.</p>
</section>
<section id="check-upstream-first-then-add-the-missing-bits" class="level2">
<h2 class="anchored" data-anchor-id="check-upstream-first-then-add-the-missing-bits">Check upstream first, then add the missing bits</h2>
<p>Pinned containers are good for reproducibility and are also time capsules. The XPU stack kept moving while I worked, so my loop for every missing path became:</p>
<ol type="1">
<li>Check current SGLang, torch-xpu, oneDNN, Intel’s images, and the XPU kernel packages.</li>
<li>Confirm whether the failure is still present in the pinned release.</li>
<li>Separate a missing platform-specific branch from a missing implementation.</li>
<li>Add the smallest overlay that makes the model correct.</li>
<li>Delete the overlay when upstream covers the same case.</li>
</ol>
<p>Step three is the one that saves weeks, and it came up immediately.</p>
<p>SGLang reads AWQ checkpoints through a component called <code>compressed-tensors</code>, which decides how packed four-bit weights get unpacked and which matrix kernel serves them. In the version I was using, two small things quietly assumed an NVIDIA GPU. A helper that rearranges packed weights into the layout the kernel expects was imported only when CUDA was available, then called later regardless. Separately, the code that picks a quantization scheme asked CUDA for the device’s compute capability before it had chosen a scheme at all, which simply fails on a machine with no CUDA device.</p>
<p>Neither of those means Intel GPUs lack a four-bit kernel. The kernel was there. The checkpoint just could not reach it, because the road to it ran through NVIDIA-only code. Adding the missing branch was enough.</p>
<p>The MTP path had the same shape. I registered the XPU attention backend in the speculative draft maps, routed the token-tree convolution to a Triton implementation that accepts tree arguments, and relaxed two helpers that rejected non-CUDA tensors even though their implementation was already Triton. Small integration fixes, not a replacement serving stack.</p>
<p>One more lesson: “the model loaded” is only the beginning of correctness. My first text-only quantization build silently omitted the vision tower and the MTP head. The library never instantiated an MTP module, so <code>save_pretrained</code> could not save tensors it did not know existed. I now build with the multimodal class, copy the MTP tensors explicitly, and verify the tensor list before any performance run.</p>
</section>
<section id="the-existing-library-primitive-was-the-fastest-kernel-i-tested" class="level2">
<h2 class="anchored" data-anchor-id="the-existing-library-primitive-was-the-fastest-kernel-i-tested">The existing library primitive was the fastest kernel I tested</h2>
<p>Once the model was correct enough to benchmark, the obvious question was which four-bit matrix path should serve the dense projections.</p>
<p>The answer was not my hand-driven kernel. On the same community AWQ checkpoint, the same two B65 cards, and the same captured 128-input/512-output shape:</p>
<p><img src="qwen38-27b/awq-path.svg" class="img-fluid" style="width:100.0%" alt="Four measured W4A16 paths on two B65 cards rise from 6.2 tokens per second for separate dequantization and matmul to 35.1 tokens per second for the existing oneDNN primitive."></p>
<p><em>Figure 1. The existing oneDNN primitive, not a new custom kernel, produced the largest measured four-bit step on this shape.</em></p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>path</th>
<th style="text-align: right;">TPOT</th>
<th style="text-align: right;">decode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>awq_dequantize</code> followed by <code>torch.matmul</code></td>
<td style="text-align: right;">161.22 ms</td>
<td style="text-align: right;">6.2 tok/s</td>
</tr>
<tr class="even">
<td><code>moe_grouped_mm_nt_xe20_w4a16</code>, driven as a dense GEMM</td>
<td style="text-align: right;">39.04 ms</td>
<td style="text-align: right;">25.6 tok/s</td>
</tr>
<tr class="odd">
<td>the same kernel with split-K</td>
<td style="text-align: right;">35.44 ms</td>
<td style="text-align: right;">28.2 tok/s</td>
</tr>
<tr class="even">
<td><code>aten::_weight_int4pack_mm_with_scales_and_zeros</code> / oneDNN</td>
<td style="text-align: right;"><strong>28.46 ms</strong></td>
<td style="text-align: right;"><strong>35.1 tok/s</strong></td>
</tr>
</tbody>
</table>
<p>That ATen primitive dispatches to oneDNN weight decompression. It needed no model-specific tuning file and, for this checkpoint layout, no second weight repack. Reading its source also explained a BF16/F16 difference I had measured: the specialized four-bit dequantization gate in the oneDNN version I used admits F16 and F32 compute types, while BF16 falls through to a more generic tile-conversion branch.</p>
<p>I spent a day pushing the hand-driven path before accepting the stop condition: if the library primitive is already close to the in-situ roofline, keep it as the baseline and move up a level. oneDNN wins this round.</p>
<p>That was a large improvement, and it exposed the next problem. The community AWQ checkpoint left the three large Gated DeltaNet projections in BF16, and those represented nearly half the bytes read during a decode step. The kernel was no longer the only question. The checkpoint itself had become part of the latency path.</p>
</section>
<section id="four-bits-is-not-really-four-bits" class="level2">
<h2 class="anchored" data-anchor-id="four-bits-is-not-really-four-bits">Four bits is not really four bits</h2>
<p>My checkpoint inventory measured the three large projections in every DeltaNet layer, input QKV, input Z, and output, at roughly 10.36 GiB in BF16. That is about 47% of the community checkpoint’s decode traffic. I nearly left them alone. Then I looked at the official FP8 release and found scale tensors for those same projections, with only the small surrounding tensors excluded. Useful prior: the model authors quantize these in their own low-precision release.</p>
<p>My AWQ build quantizes 24.33 billion parameters with asymmetric group-128 W4A16. Per-group scales and zero points bring the stored cost of those weights to 4.16 bits per parameter. Another 3.45 billion parameters stay BF16: embeddings, output head, norms, small DeltaNet gates, vision tower, and MTP head. Across the full checkpoint that averages 5.63 bits per parameter, or 18.2 GiB.</p>
<p>I did not arrive at group 128 immediately. The first all-four-bit build used group 32. It had finer quantization groups and fewer total model bytes than the community checkpoint, and it ran slower. Two measurements explained the sign:</p>
<ul>
<li>Group 32 reads four times as many scale and zero-point groups.</li>
<li>On the same <code>down_proj</code> tensor at <code>M=1</code>, oneDNN moved group-32 data at 383 GB/s and group-128 data at 505 GB/s. The matching BF16 GEMV reached 589 GB/s.</li>
</ul>
<p>Group size was not just a quality setting. It was a serving-layout decision, and re-quantizing at 128 was worth more than another day of kernel changes.</p>
<p>There is a partial victory hiding here. Quantizing the DeltaNet projections cut measured decode traffic from 21.82 GiB to 14.19 GiB, about 35%. In the matching TP2 run, throughput moved from 35.4 to 38.5 tok/s, about 9%.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>TP2 checkpoint, same short-context setup</th>
<th style="text-align: right;">bytes read per step</th>
<th style="text-align: right;">TPOT</th>
<th style="text-align: right;">decode</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>community AWQ, DeltaNet projections BF16</td>
<td style="text-align: right;">21.82 GiB</td>
<td style="text-align: right;">28.24 ms</td>
<td style="text-align: right;">35.4 tok/s</td>
</tr>
<tr class="even">
<td>my group-128 AWQ, DeltaNet projections INT4</td>
<td style="text-align: right;">14.19 GiB</td>
<td style="text-align: right;">25.95 ms</td>
<td style="text-align: right;">38.5 tok/s</td>
</tr>
</tbody>
</table>
<p><em>Thirty-five percent fewer bytes produced about nine percent more tokens per second. The byte model found the opportunity, but the runtime said those newly quantized projection shapes were not behaving like ordinary dense four-bit GEMMs.</em></p>
<p>That gap is still open. The merged DeltaNet projection at TP2 has a shape unlike the dense FFN projections, and it is the leading suspect. I would rather publish the unexplained result than adjust the story until the arithmetic looks neat.</p>
</section>
<section id="graph-capture-changes-both-performance-and-observability" class="level2">
<h2 class="anchored" data-anchor-id="graph-capture-changes-both-performance-and-observability">Graph capture changes both performance and observability</h2>
<p>Decode is a long chain of small operations. Graph replay removes much of the per-operation submission cost, so graph capture is part of the setup I actually use, not an optional benchmark trick. Earlier work on two other models on these same cards measured it as a first-order improvement. For Qwen3.8 I do not have a clean graph-on/graph-off comparison, so I attach no new percentage to it.</p>
<p>Capture also changes what instrumentation means. A Python-side counter that gets incremented while the graph is being captured can replay the device work forever without ever incrementing the Python value again. I once had a fast collective serving happily inside the graph while its own log insisted <code>served=0</code>.</p>
<p>The only trustworthy proof was controlled removal:</p>
<ul>
<li>build the same graph with the path enabled;</li>
<li>build it again with exactly that path disabled;</li>
<li>run the same shape after compilation;</li>
<li>require the timing to move by more than the quiet-box noise floor.</li>
</ul>
<p>One of those A/B tests was for a small collective operation. When the model is split across four cards, every layer has to sum partial results from all of them, an operation called an all-reduce. During decode that message is tiny: one token at hidden size 5,120 in BF16 is about 10 KiB. At that size almost none of the time goes into moving bytes. It goes into the fixed cost of setting up the exchange and getting the cards to agree they are ready.</p>
<p>So a leaner path for small messages is worth having. The one I use is built on shared memory that the rank processes map directly, capped at 64 KiB, handing anything larger (prefill, mostly) back to the standard collective. Disabling it in the saved TP4 A/B run cost 4.41 ms per step.</p>
<p>Because it maps shared-memory handles across those processes, it needs <code>SYS_PTRACE</code> and <code>seccomp=unconfined</code> in my container. Those permissions widen what the container can do. They are required for this optional collective, not for running Qwen3.8 in general, so remove them and disable the path if that tradeoff does not suit you.</p>
<p>Hybrid models have another memory pool to watch. The recurrent state pool competes with the KV cache and can bound concurrency before the ordinary request limit does. I once configured it below the number of slots a single request needs and got a server reporting zero runnable requests, with an error that mostly talked about memory. Raising the request limit was never going to help. There was nowhere to put the recurrent state.</p>
</section>
<section id="the-trace-blamed-the-wrong-component" class="level2">
<h2 class="anchored" data-anchor-id="the-trace-blamed-the-wrong-component">The trace blamed the wrong component</h2>
<p>At one point I fit TP2 and TP4 measurements to a simple model with a sharded weight term and a constant term. The fit suggested roughly 12 ms that did not shrink with more cards. Host overhead or graph replay looked guilty.</p>
<p>Rather than apportion a busy trace, I priced components by removal on the real captured graph. Replace one component with shape-matched zeros, keep the rest of the graph and the collectives intact, and measure against an unchanged repeat. This does not produce a perfect additive profile, since collectives overlap some module rows, but it answers the causal question: what disappears if this component is removed?</p>
<p>Starting from a 28.59 ms B65 TP2 run:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th>removed component</th>
<th style="text-align: right;">measured cost</th>
<th style="text-align: right;">share of the step</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>dense MLP bodies across 64 layers</td>
<td style="text-align: right;"><strong>12.37 ms</strong></td>
<td style="text-align: right;"><strong>43% measured</strong></td>
</tr>
<tr class="even">
<td>attention sublayers across 64 layers</td>
<td style="text-align: right;"><strong>10.39 ms</strong></td>
<td style="text-align: right;"><strong>36% measured</strong></td>
</tr>
<tr class="odd">
<td>of which attention and GDN kernels</td>
<td style="text-align: right;">2.24 ms</td>
<td style="text-align: right;">8% measured</td>
</tr>
<tr class="even">
<td>of which projections, gates, RoPE, and collectives</td>
<td style="text-align: right;">8.15 ms</td>
<td style="text-align: right;">28% measured</td>
</tr>
<tr class="odd">
<td>layer-stack all-reduces, overlapping the rows above</td>
<td style="text-align: right;">3.82 ms</td>
<td style="text-align: right;">13% measured</td>
</tr>
<tr class="even">
<td>sampling path</td>
<td style="text-align: right;">0.37 ms</td>
<td style="text-align: right;">1% measured</td>
</tr>
</tbody>
</table>
<p>The supposedly fixed host term was mostly dense MLP device work, whose poor multi-card scaling made a two-point fit look constant. The DeltaNet recurrence itself was small. Had I trusted the fit, I would probably have spent another week optimizing the wrong layer family.</p>
<p>That changed the order of future work: merged four-bit projection shapes first, then dense scaling, then whatever a fresh removal budget turns up. The recurrence is not free, but it is not the first problem.</p>
</section>
<section id="the-final-latency-distribution-is-pleasantly-boring" class="level2">
<h2 class="anchored" data-anchor-id="the-final-latency-distribution-is-pleasantly-boring">The final latency distribution is pleasantly boring</h2>
<p>A mean TPOT can hide an ugly tail, so I measured the inter-token latency distribution for the final AWQ release. Each point below summarizes 1,023 inter-token intervals from the second run of a 1,024-token output, concurrency one, graph capture on.</p>
<p><img src="qwen38-27b/awq-itl-percentiles.svg" class="img-fluid" style="width:100.0%" alt="Median-to-p99 inter-token latency stays narrow on both two and four B65 cards, at short and 8K prompts. TP2 ranges from roughly 26.2 to 27.0 ms, while TP4 ranges from roughly 19.1 to 19.7 ms."></p>
<p><em>Figure 2. Across the short and 8K prompts, p99 stayed within 0.66 ms of the median on TP2 and within 0.57 ms on TP4.</em></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>GPUs / TP</th>
<th style="text-align: right;">prompt</th>
<th style="text-align: right;">median ITL</th>
<th style="text-align: right;">p90</th>
<th style="text-align: right;">p99</th>
<th style="text-align: right;">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2x B65 / TP2</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">26.16 ms</td>
<td style="text-align: right;">26.51 ms</td>
<td style="text-align: right;">26.82 ms</td>
<td style="text-align: right;">32.32 ms</td>
</tr>
<tr class="even">
<td>2x B65 / TP2</td>
<td style="text-align: right;">8K</td>
<td style="text-align: right;">26.41 ms</td>
<td style="text-align: right;">26.63 ms</td>
<td style="text-align: right;">26.97 ms</td>
<td style="text-align: right;">32.40 ms</td>
</tr>
<tr class="odd">
<td>4x B65 / TP4</td>
<td style="text-align: right;">256</td>
<td style="text-align: right;">19.10 ms</td>
<td style="text-align: right;">19.37 ms</td>
<td style="text-align: right;">19.67 ms</td>
<td style="text-align: right;">22.16 ms</td>
</tr>
<tr class="even">
<td>4x B65 / TP4</td>
<td style="text-align: right;">8K</td>
<td style="text-align: right;">19.17 ms</td>
<td style="text-align: right;">19.37 ms</td>
<td style="text-align: right;">19.60 ms</td>
<td style="text-align: right;">22.14 ms</td>
</tr>
</tbody>
</table>
<p>This is the kind of graph I like: not dramatic, just steady. It supports a more useful statement than “the model does 52 tok/s”. At these two contexts and this concurrency, the ordinary token-to-token experience hides no large tail.</p>
</section>
<section id="what-might-b70-do" class="level2">
<h2 class="anchored" data-anchor-id="what-might-b70-do">What might B70 do?</h2>
<p>I have not measured Qwen3.8-27B on B70, so an exact B70 bar would be fiction. There are two useful boundaries though.</p>
<p>The conservative edge assumes no decode uplift at all, since B65 and B70 share the same advertised 608 GB/s of memory bandwidth. The optimistic edge borrows the largest B70-over-B65 decode ratio I measured on two other models, 1.273x. That is deliberately rough: Qwen3.8 is dense while those models are sparse hybrids, so their scaling does not automatically transfer.</p>
<p><img src="qwen38-27b/b65-b70-scenarios.svg" class="img-fluid" style="width:100.0%" alt="Measured B65 decode is 37.8 tokens per second at TP2 and 52.1 at TP4. Hatched, explicitly unmeasured B70 estimate bands span 37.8 to 48.1 and 52.1 to 66.3 tokens per second."></p>
<p><em>Figure 3. The B70 range is a planning aid, not a benchmark. The lower edge assumes equal bandwidth means equal decode; the upper edge applies the largest uplift seen on two earlier models.</em></p>
<p>Prefill has a better reason to move, since the B70 has more Xe2 cores and roughly 1.86x the advertised dense INT8 compute. Even there I would not simply multiply the measured result by 1.86. Attention, dequantization, collectives, and achieved occupancy do not all scale with peak matrix throughput. The next honest graph is a measured one.</p>
</section>
<section id="a-quick-detour-through-the-other-models" class="level2">
<h2 class="anchored" data-anchor-id="a-quick-detour-through-the-other-models">A quick detour through the other models</h2>
<p>Qwen3.8 was the fourth model in this line of work. The earlier three are not apples-to-apples competitors, since they use different architectures, card counts, TP sizes, and workloads. Their value here is showing which methods survived contact with another model.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>model</th>
<th>one useful result</th>
<th>what I brought forward</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Qwen3-Coder-Next 80B-A3B</td>
<td><strong>100.9 tok/s</strong>, B70 TP4, 8K/1K c=1</td>
<td>graph replay, TP-specific tuning, small-collective latency, counting the weights actually used per token</td>
</tr>
<tr class="even">
<td>Ornith 1.0 35B</td>
<td><strong>106.8 tok/s</strong>, B70 TP2, 8K/1K c=1</td>
<td>check packed quantization against real tensors, and never assume a Qwen attention setting helps another hybrid model</td>
</tr>
<tr class="odd">
<td>DeepSeek-V4-Flash</td>
<td><strong>35.1 tok/s</strong> short-context decode and 2,355 tok/s at 8K prefill on 8x B70; a later single-stream test fit 801,024 usable tokens at a 1M setting</td>
<td>start with upstream, measure cold prefill separately, remove components to find where the time really goes</td>
</tr>
</tbody>
</table>
<p>The most useful warning came from Ornith. It looked similar to Qwen: hybrid attention, Gated DeltaNet, packed four-bit experts. Yet its asymmetric zero points changed the correctness contract, its router already used a good XPU top-k path, and the Qwen attention override made it slower. The method transferred; the configuration did not.</p>
<p>Those rows are signposts, not a cross-model contest. Each model deserves its own post, and I plan to write them. This one is about Qwen3.8 and the method I used to work out what it needed.</p>
<p>That is also why I do not present a bag of “Xe2 optimizations” to enable all at once. Graph capture, rooflines, proof that a fast path actually ran, and controlled A/Bs are methods. A tile size, context cutoff, or packed layout belongs to the exact model, card, and TP combination that earned it.</p>
</section>
<section id="what-were-codex-and-claude-actually-useful-for" class="level2">
<h2 class="anchored" data-anchor-id="what-were-codex-and-claude-actually-useful-for">What were Codex and Claude actually useful for?</h2>
<p>I used coding agents extensively during this work, mainly Codex and Claude. They were useful in a narrower and more practical way than “the agents wrote the optimization”.</p>
<ul>
<li><strong>Reading an unreasonable amount of source.</strong> One investigation followed the SYCL grouped GEMM through its tile policy and reorder atoms, then compared it against oneDNN. That is how I learned the clever four-bit conversion I was about to implement already existed.</li>
<li><strong>Surveying an API surface.</strong> An agent enumerated quantized primitives with real XPU dispatch, their schemas, and their layout contracts, which quickly separated usable operators from names that merely sounded relevant.</li>
<li><strong>Building harnesses from a strict specification.</strong> The speculative-decoding harness refuses failed requests and keeps cache-sensitive natural-text tests separate from random-token kernel isolation.</li>
<li><strong>Running serialized campaigns.</strong> Tuning many shapes is boring but valuable, and it is a good background job when only one process may own the GPUs.</li>
</ul>
<p>They were also entirely capable of producing a confident conclusion from an empty log. Twice a container had stopped and the missing output was treated as a finding. A <code>pkill -f</code> pattern matched the replacement command itself four times. One benchmark reported a rejected over-context request as zeros, which looked like an amazing performance result for a few seconds.</p>
<p>The defense was not asking an agent to be more careful. It was making the harness fail loudly, recording the exact setup and run number, keeping retractions beside results, and refusing to print metrics for a rejected request. The human job stayed arbitration: one benchmark on the GPUs at a time, one changed variable, and no number without a saved log.</p>
</section>
<section id="fast-gibberish-is-still-gibberish" class="level2">
<h2 class="anchored" data-anchor-id="fast-gibberish-is-still-gibberish">Fast gibberish is still gibberish</h2>
<p>Two quantization mistakes produced clean server starts and output consisting almost entirely of exclamation marks.</p>
<p>First, the text-only model class changed module prefixes. Weight loading had a name-translation layer, but the quantization ignore list did not, so exclusions silently missed their targets.</p>
<p>Then the quantizer added the container module <code>layers.N.linear_attn</code> to the ignore list, because the container itself was not a <code>Linear</code>. The runtime matched ignore entries by substring, so that one entry hid every projection beneath it. Packed tensors existed in the checkpoint and were never loaded into those linears.</p>
<p>Both cases now fail at build time. More importantly, I compare packed dequantization against an independent float64 reference on real tensors. Shape checks alone are not enough. A wrong packed orientation can be shape-valid and still produce fluent-looking, numerically wrong output.</p>
<p>The final group-128 AWQ checkpoint passed health, determinism, and coherence checks on code, reasoning, factual, and summarization prompts. Against the BF16 reference:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>quality check</th>
<th style="text-align: right;">result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>mean rank of the BF16 reference token on aligned steps</td>
<td style="text-align: right;"><strong>1.0000</strong></td>
</tr>
<tr class="even">
<td>BF16 reference token outside AWQ top 8</td>
<td style="text-align: right;"><strong>0</strong></td>
</tr>
<tr class="odd">
<td>mean KL on aligned steps</td>
<td style="text-align: right;">0.0201</td>
</tr>
<tr class="even">
<td>prefill perplexity</td>
<td style="text-align: right;">8.87 → <strong>9.33</strong>, +5.2%</td>
</tr>
<tr class="odd">
<td>prompts whose greedy text diverged</td>
<td style="text-align: right;">8 of 8</td>
</tr>
<tr class="even">
<td>aligned steps after divergence</td>
<td style="text-align: right;">71 of 957</td>
</tr>
</tbody>
</table>
<p>Exact argmax agreement applies only where the sequences are still aligned. Every greedy sequence eventually diverged, leaving 7.4% of steps directly comparable. The honest takeaway is therefore modest: the quantized model stays close to BF16 before divergence, at a measured +0.46 prefill-perplexity cost. It is still a four-bit model, not an exact BF16 drop-in.</p>
<p>I also have an absolute IFEval result, but no current BF16 run through the same harness and scored subset, and I will not compare it against an older result that skipped a different set of instruction types.</p>
<p>Multimodal inference works. The checkpoint keeps the vision tower in BF16, images load, and the model answers questions about them. What I have not done is score it against a broad image benchmark suite, so I can say the capability is present and working without yet quantifying what the four-bit text weights cost it. The MTP path is enabled as well, though acceptance rates and end-to-end benefit on natural coding prompts still need a proper campaign. Random token IDs are useful for defeating the prefix cache, but they pin speculative yield near its minimum and cannot answer whether MTP helps a real session.</p>
</section>
<section id="what-still-does-not-make-sense" class="level2">
<h2 class="anchored" data-anchor-id="what-still-does-not-make-sense">What still does not make sense?</h2>
<p>The byte model says the fully quantized DeltaNet projections should save more time than they do. Three independent views agree the gap is real: checkpoint-aware projection, same-shape kernel rates, and component removal. None of them yet explains why the merged projection behaves so differently from the dense FFN path.</p>
<p>The next work is concrete:</p>
<ol type="1">
<li>Measure Qwen3.8 on B70 directly, and replace the estimated B70 range in this post with real numbers.</li>
<li>Profile the merged DeltaNet four-bit shapes inside the running server, not only as standalone GEMMs.</li>
<li>Repeat the component-removal measurements afterwards, since these rankings expire whenever an algorithm changes.</li>
<li>Measure how often MTP’s speculated tokens are accepted during real coding-agent sessions rather than synthetic prompts.</li>
<li>Put numbers on the vision path with a full multimodal quality suite.</li>
</ol>
<p>What I would carry to the next model is the method rather than this configuration: check upstream first, count bytes from the checkpoint, keep the vendor library as the baseline, verify instruction and layout legality before designing a tile, prove every fast path actually served, and measure with graph capture on, the way the model will be used day to day.</p>
<p>That process is slower than collecting one exciting number, but it made the next model much faster to understand. More importantly for me, Qwen3.8 is now a local coding-agent backend I can use without thinking about every token it generates, which was the point of the exercise.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/blog\.rahul\.onl");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<script src="https://utteranc.es/client.js" repo="rahulunair/myblog" issue-term="pathname" theme="github-light" crossorigin="anonymous" async="">
</script>
</div> <!-- /content -->




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>